import express from "express";
import fetch from "node-fetch";
import fs from "fs";
import path from "path";
import crypto from "crypto";
import { spawn } from "child_process";

const app = express();
app.use(express.json({ limit: "10mb" }));

// CORS
app.use((req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS, GET");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.sendStatus(204);
  next();
});

const WORK_DIR = "/tmp/ar";
fs.mkdirSync(WORK_DIR, { recursive: true });

const PUBLIC_BASE_URL =
  process.env.PUBLIC_BASE_URL || "https://nfs-ar-usdz.onrender.com";

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, { stdio: "inherit", ...opts });
    p.on("error", reject);
    p.on("close", (code) =>
      code === 0 ? resolve() : reject(new Error(`${cmd} exited ${code}`))
    );
  });
}

app.get("/", (req, res) => res.status(200).send("ok"));

app.post("/build-usdz", async (req, res) => {
  try {
    const { imageUrl, widthCm, heightCm } = req.body;
    if (!imageUrl || !widthCm || !heightCm) {
      return res.status(400).json({ ok: false, reason: "missing_params" });
    }

    const id = crypto.randomUUID();

    const imgPath = path.join(WORK_DIR, `${id}.png`);
    const usdPath = path.join(WORK_DIR, `${id}.usd`);
    const usdzPath = path.join(WORK_DIR, `${id}.usdz`);

    // 1) download image
    const r = await fetch(imageUrl);
    if (!r.ok) throw new Error("image_download_failed");
    fs.writeFileSync(imgPath, Buffer.from(await r.arrayBuffer()));

    // 2) Blender -> USD + texture.png (generated by make_usd.py)
    await run("blender", [
      "-b",
      "-P",
      "/app/make_usd.py",
      "--",
      imgPath,
      usdPath,
      String(widthCm),
      String(heightCm),
    ]);

    const texturePath = path.join(WORK_DIR, "texture.png");
    if (!fs.existsSync(usdPath)) throw new Error("usd_missing");
    if (!fs.existsSync(texturePath)) throw new Error("texture_missing");

    // 3) Package into .usdz using ZIP (NO compression)
    const pkgDir = path.join(WORK_DIR, `${id}_pkg`);
    fs.mkdirSync(pkgDir, { recursive: true });

    fs.copyFileSync(usdPath, path.join(pkgDir, `${id}.usd`));
    fs.copyFileSync(texturePath, path.join(pkgDir, "texture.png"));

    // zip -0 = store (no compression) which is what USDZ needs
    await run("zip", ["-0", "-r", usdzPath, "."], { cwd: pkgDir });

    // cleanup temp folder
    try { fs.rmSync(pkgDir, { recursive: true, force: true }); } catch {}

    return res.json({
      ok: true,
      usdzUrl: `${PUBLIC_BASE_URL}/usdz/${id}.usdz`,
    });

  } catch (e) {
    console.error("BUILD_USDZ_ERROR:", e);
    return res.status(500).json({
      ok: false,
      reason: "server_error",
      message: String(e?.message || e),
    });
  }
});

app.use(
  "/usdz",
  express.static(WORK_DIR, {
    setHeaders(res, p) {
      if (p.toLowerCase().endsWith(".usdz")) {
        res.setHeader("Content-Type", "model/vnd.usdz+zip");
      }
    },
  })
);

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("USDZ server running on port", PORT));
